### ISSUE TITLE
Raster Examples

### ISSUE THREAD

**Issue by gspeed0689** [UtrechtUniversity/gis-python-power#2]
Please add raster examples we can show

**Comment by gspeed0689** [comment]
My first example is to adapt my previous Sentinel 2 imagery repository
https://github.com/gspeed0689/Benelux-Sentinel2-RGBI-NDVI

**Comment by jelletreep** [comment]
From the geospatial python course by the escience center:
https://carpentries-incubator.github.io/geospatial-python/05-access-data.html
https://carpentries-incubator.github.io/geospatial-python/06-raster-intro.html

Following your example, the NDVI can be done on sentinel data that is gathered directly from the API using `pystac_client` library and read in using rioxarray

**Comment by jelletreep** [comment]
Proposed topics to discuss:

- Reading raster file (rioxarray/rasterio)
- Exploring file structure (Dataset class)
    - visualizing bands
    - extracting bands
- Reprojecting rasters
- Cropping rasters
- Composing RGB image
- NDVI calculation and raster math operations
- plot statistics (histogram)
- classification


Main concluding messages
Advantages (repeatable, exact, scalable, publishable)

**Comment by AristotleKandylas** [comment]
Topics have been already included to the workshop material
