### ISSUE TITLE
Vector Examples

### ISSUE THREAD

**Issue by gspeed0689** [UtrechtUniversity/gis-python-power#3]
Please add your vector examples here.

For example data, I have downloaded some Open Street Map data from Geofabrik to our  development folder.

**Comment by gspeed0689** [comment]
In my personal time soon I am making a video on the NS train network and ticket prices, and the notebooks I used to generate that, if its ready in time I can use that as an example.

**Comment by MaisamMD** [comment]
On Kaggle you can find examples ( some hardcoded but more notebooks) like the following one:

https://www.kaggle.com/code/nilaychauhan/getting-started-with-geospatial-data

**Comment by AristotleKandylas** [comment]
i am closing this issue as we have included all the necessary material to our repo
