### ISSUE TITLE
LiDAR examples

### ISSUE THREAD

**Issue by gspeed0689** [UtrechtUniversity/gis-python-power#4]
What ideas do you have for LiDAR data?

I have copied AHN 4 LiDAR data to our development folder, I will cut that data down to just the Utrecht Science Park so we're not distributing 18GB worth of data.

**Comment by MaisamMD** [comment]
Why we don't use available examples and tweak them as we need:

https://www.kaggle.com/code/sakshaymahna/lidar-data-visualization

**Comment by AristotleKandylas** [comment]
@gspeed0689 & @jelletreep  closing this one as we have agreed to omit this part from our practical session.

Kind Regards,
Aristotelis
